language: python
python:
- '2.7'
before_script:
- yes | python setup.py install
- git clone https://github.com/uc-cdis/dictionaryutils; cd dictionaryutils
script:
- "./run_tests.sh"
deploy:
  provider: s3
  access_key_id: AKIAZRNPHKJIAGBSGXN3
  secret_access_key:
    secure: Mo3aVLrumCfcPWrpoLavuc7jX4cA4DJ7qw40DWvy8DF5XHUM7z40L3TFskN/8mY56TkHqGsMw2XINtD5gFAqR82vcR6T2j6FSkAc8r3H/bnheBYxfOc+QG8jtAm5UwsDN7TJ1h32QKbS13szn+oL/I6/hFblxixnA6iSZKMdji3rpdbBPRsh8SaFxA/NefkvKhNQuEXIGNvjO0gYTaIj3nQnwwm3t4H1wE2jxbtqG9r39yaNKFaJzwnUP1inzc2edNOKLunITWKNoxW9eJDOKlgBAGcp1SasdNT2qNu3HcFwKCY+nMhNKWuTYDVWkOHu6p5+UFOsINnr9jmbgkvKiMtInUONcVGFx8zvr+fdIfLWqvJFdhBJpL+BpleYb2mPRLf2UfhdabSjHjPDUG2jhZl/bXGox8KgoY+PSQSjQgPMlsfvNJxgND2J1JPbCppdTc3asGJtluk9YWzM36dPBVsdabgl4sb1JKpPOor2Z2CshZLpI9huqZERlduSrhh8UOSORPdq1FlsW4EO1yFmngTEIYRYNrlFKkg0ie3TPI+bkiDeu9ud4y3LIoFkZNAIQCut5BW+4XaPZ5lwBupkj2+DUQZWx0hW3EjI3dwjvHw3SHzanrduJEWnUUFbNyWS6beN2Ue86OR+AcbPp1baEA/7qLLWxzdinIhanQkoIAI=
  bucket: dictionary-artifacts
  local-dir: artifacts
  upload-dir: charlie-datadictionary/$TRAVIS_BRANCH
  skip_cleanup: true
  on:
    repo: uc-cdis/Charlie_datadictionary
    all_branches: true
env:
  global:
    secure: mUJ5s6uIBKLlBaS3Cz8Qi579APKdxiWhAxMqVOSi8PmIPVfRMtOCBcxvqABqCNrxGa9aKFxOkcnuorDG79kp3cln1nGugKOf/hab41KJVb1VaOXhRiBvyieni+fpr2cs4jZxWmtmgix9GgnrUtCP/ctKerZPkixdtHgqmJKfdKqpH5ZVYWoU+eGiTxYaIs7qy+wY2HfWxfm4Ik/NfdBEmI2oE9Y/iRQiL+rlWQvrex6BLaTkgKjVX3AWfrWgBlTwW4hotmhO/ZJqB86SqC4Iz/g2gQJfAS18pTUUtA1kSBMzwBsTBY+n8QeUGnlRbB71yY5rSDis2CnCQLS4jtioNJZi0vpbQ9cdym7gPwxsucMyuWvnU9dEajgp3NrM3uwA/gonjjbFzGsrWHmgEPT0Y9wTShx7n0LaLvrQeY4I4WhnRT1nLMJso0rcE6wXCnZqHnz4vCNX4MbRykgdLjaqFWIA6qSB3Qw0fpdAhyQzw+YEoZKriy6BAusM59IxB4jx2PFuhHrnJkbsA3qFTkMjXXCLN3/zFDvpqCdlw3PInEfR7GnfjGiwvpbtJQY0u59QFmmvhGqPyPLOP8doRljCpknXPpXh959egyIha8A77dYDj9VIbjcOWkMEgjQ5xwvu2Or0vfsaXB9H3udyfa0W2uVBHYge/Q5yBQNYV5bg+Og=
