language: python
python:
- '2.7'
before_script:
- yes | python setup.py install
- git clone https://github.com/uc-cdis/dictionaryutils; cd dictionaryutils
script:
- "./run_tests.sh"
deploy:
  provider: s3
  access_key_id: AKIAZRNPHKJIGILBEKFN
  secret_access_key:
    secure: hVqTw+tiYa5bxECf4Sf8CYMsYsR6Rcwvq17RX7Gw1wctCYGm901wlDeiCmpcFvaT8dDy/PYCVyf23Asf57tfipNenMKZGtjb8E/LAhIfA4eKtaavl7cALe9ZOG1xPzA7WPzUp/SkHBbO7FceXlNOYQyaZMUP8Gn1RJGiBiW8TUOZwqh5omjTCzZkBh2IL+eekU/OA46PQRemcPcyBxPmGhyAs3mH2HA1jDTzRwlQ9r5y/bUBZ1VSq3HebZ1chGq5ckWk6dy2pX/t6onFuVC2pcQqeOvNxbolthFzUW17DizSKYc5zEjMk5Jl9uWDhOM7bAm6MflPQgH6+jg3JtQzsewl6SHc6ly5Y0/am+5tIzkvZYt4m86nj5QqdUoITqkG+hGWbe2f3epaU0SUENEoVsK/LoM93NK/luIuLEYPo8S89Ih43NmdSj9kpe3nFJmjFnPrZJGK9o+yHkT3kCYa4DSQCMxydUawABcI+tLowBLpnBzDzkevW8cirHfIzrkrDmxZnzwvUzcSSSPeJaMa1PT6jeXTxEeBSLovoi4lKgsoakkQTgLcyRfVOx7UvgUBro1LY/VOWYhcvwQUUYEPhUx/7wi/09hc7wVY5vZVfKe2kUZB+jxw6eO93NhDFZaRuiwFYxGwI6v3KUUBsl3tTWVbrjZFG+tx6wkVgGiBGx4=
  bucket: dictionary-artifacts
  local-dir: artifacts
  upload-dir: charlie-datadictionary/$TRAVIS_BRANCH
  skip_cleanup: true
  on:
    repo: uc-cdis/Charlie_datadictionary
    all_branches: true
