language: python
python:
- '2.7'
before_script:
- yes | python setup.py install
- git clone https://github.com/uc-cdis/dictionaryutils; cd dictionaryutils
script:
- "./run_tests.sh"
deploy:
  provider: s3
  access_key_id: AKIAZRNPHKJIGILBEKFN
  secret_access_key:
    secure: mo7fWYvww4tnqa1lcsjJH+3NCjsA8XAVcFTsEMxl2AG+4Tfn1QXJolliD1T0gRfk2WXPHlgs83Gyo2u+azl0L4OcWLm6gApVOngCYOaiYyO0EhoMXQQml6/YZr2co09Ew50LO95fSWPsu2aNwXBe3LjrQCHQ1X9KZsPQFT9ooy+Fkq7RVmOggG158LAh0ELEy0iq8qy9nnmvgisW7mTMW4HITdLuDyNyDzIGp3fCSFv/0Zannx96PJztWsOyYiwKqfnSf9+Kqp6SLgHvPrSdCktypWhGoaxRO7i6vYPH4Z8z5+mjAxnPT208EqCbS+tJ4+ihG6r1FvhT2OzMb0WjggCB+yUZyjgyBNaz33w9Ag37qGmHGyw9J262hZj3h1wdBjGGM7dX8YGz1+63hM4YN+wWuiK2of4ryOmK1rRkR505IIs1QbXZtcHu/zha9NhjYYzXkh+gxfVoI8Ita1OXGzuvFDBGHAYjcbvJG+pPOKyAdc+vkggpuqQQaLywYJYrtDm5mnN/0PGxNv5o4wst1ZvKwepTW6+dvKwqNQ1tUyp3IiYMj21813sBrevzroN8aUIwPrvaIGa1IND1OyQ3VH3GOFX2nmDayERO0TxTmNK82ntMMJXsLPSir8+i8lbWSJZ2o3niCiy+m2X4K2/CF+YZxzwrYyfUR6M0tNj4T+k=
  bucket: dictionary-artifacts
  local-dir: artifacts
  upload-dir: charlie-datadictionary/$TRAVIS_BRANCH
  skip_cleanup: true
  on:
    repo: uc-cdis/Charlie_datadictionary
    all_branches: true
