language: python
python:
- '2.7'
before_script:
- yes | python setup.py install
- git clone https://github.com/uc-cdis/dictionaryutils; cd dictionaryutils
script:
- "./run_tests.sh"
deploy:
  provider: s3
  access_key_id: AKIAZRNPHKJIAGBSGXN3
  bucket: dictionary-artifacts
  local-dir: artifacts
  upload-dir: charlie-datadictionary/$TRAVIS_BRANCH
  skip_cleanup: true
  on:
    repo: uc-cdis/Charlie_datadictionary
    all_branches: true
  secret_access_key:
    secure: l9QJu9uq8qJVOaZSqh8slAKtqA73PXcSoyZWDOI/JlQwcRzT07/IAP8e+fVkExKntIC19+xGJ+612NVZHKaVaMml2wkPJFn2WCW9JD3uTS1Uxn5mnjfE6uv/FYXRAzs83iusd8lmfk6sljROmgF7o32C2uZr2Ehmz5buYhHSo3iKfvVoyrnEv5duVVAXyPrGbSLP4dRXDEsWEcc/N42C7iS8IQb0RQqMYDF9L6S9kmq02ws5hflbI4DMhhWzWojSO7nGtcGOAL1tBchdkJfmF6/mtpnVHVQUgOh6+eB7zHFFykL/P/rzVbIhUQRuvViaNW1pPRoVU700jZNAPCiVNnAtHRaqbgzqgrPrJ5kK5XR64GbdNRTmutCvnsNXRnozea8ZKpRyldv/DYXQfn5fUEjpC3DRK9QBYqrJm9pwFYxKbp0A1RHXaffbdrz336WJrG7CEGtszvR602YxO45/cFXOrHHlF0pDP3jeEWySzwc6G3CzT7nF/XsyU/XDG2zBgbSfvOc9Okveo8xeC7p43lbhQhMz07cXUTtPQ77/MFvnqml/6pAkW6CCXUWNxNGf1naPmgVjm9zVvvytmchPllbnb7S4PKkL0Oe/+zFi6bW/Wqs1mF85jGYaRO3z7/cw+JlRln+yuox43m7p7y/l7YWscek4g/84eMGtQ43TUdU=
