language: python
python:
- '2.7'
before_script:
- yes | python setup.py install
- git clone https://github.com/uc-cdis/dictionaryutils; cd dictionaryutils
script:
- "./run_tests.sh"
deploy:
  provider: s3
  access_key_id: AKIAZRNPHKJIGILBEKFN
  secret_access_key:
    secure: oklaj3B2alq6841ki4C6MFM+yNOk8PoR/Xj4J2GcTyI2PFeLLN6y7xgbputY9pZDJBMnA+Wvk6LRGdQwl8KZ0oYzke+GPz8n1IZ9KaOg91b+m5751qAqOvTCdWKzny0yNwWAZrffe7MVV6lB0qEjHmVj0srGTTzCSNG8J39fbi82crG/SWgN23cd+lusDut5pqlvBn1pqKq8awUGqROsgq2B9BMt5PnGiwgUvY5+NmNYMBRJrS6Kuu4oMSlqpC/QpY+IyfByxxsBhaHUcRcO6ytEMgVZfUl4aelrC7wJ5M9s182R4b4j2cx1s5Szg+Q82nNveOeZSY6J0on3N8g4NxXw6QoLttCqpxQTeLw3X5VPbkTmez1EwZ4YBek9bhZCND2Pxkq5Sgt1Pi6nAZPVv/l72nYaVPgLACoaa1Cg8GARMoNDPzi4Kicgcy1GpkDLyIwbddNqcjBIARVbcv9TyYvaj8dHxrjKpqbd1gVjetLQFukOiEDqdBYKCmh4CYqDWfVo0k6csPd3L4fDL4beTMzV7shZh6uSB6m6FFjpQFp7aPGejbM+UjUpSkgDKESK0+fjeBxKs8KgajJOhwdOfAVlLrNjXxb8AYEJqnIs2WNYebuKnFlTVwFV5OG5F6g8o9MPPKsBQX4tqk2Npb/7UHyXY+1AydRIbFjl74w9b6w=
  bucket: dictionary-artifacts
  local-dir: artifacts
  upload-dir: charlie-datadictionary/$TRAVIS_BRANCH
  skip_cleanup: true
  on:
    repo: uc-cdis/Charlie_datadictionary
    all_branches: true
